services:
  - type: web
    plan: free
    name: makichi
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/Strelizia-007/Maki.git
    branch: main
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: UPDATE_CHANNEL
        sync: false
      - key: UPDATECHANNEL_ID
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: RKN_PIC
        sync: false
      - key: ADMIN
        sync: false
      
